rudak_cms_admin:
    path:     /admin/cms
    defaults: { _controller: "RudakCmsBundle:Admin:index" }

rudak_cms_admin_cms_page:
    resource: "@RudakCmsBundle/Resources/config/routing/page.yml"
    prefix:   /admin/cms/page

rudak_cms_admin_cms_category:
    resource: "@RudakCmsBundle/Resources/config/routing/category.yml"
    prefix:   /admin/cms/category

