admin_cms_category:
    path:     /
    defaults: { _controller: "RudakCmsBundle:Category:index" }

admin_cms_category_show:
    path:     /{id}/show
    defaults: { _controller: "RudakCmsBundle:Category:show" }

admin_cms_category_new:
    path:     /new
    defaults: { _controller: "RudakCmsBundle:Category:new" }

admin_cms_category_create:
    path:     /create
    defaults: { _controller: "RudakCmsBundle:Category:create" }
    methods:  POST

admin_cms_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "RudakCmsBundle:Category:edit" }

admin_cms_category_update:
    path:     /{id}/update
    defaults: { _controller: "RudakCmsBundle:Category:update" }
    methods:  [POST, PUT]

admin_cms_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "RudakCmsBundle:Category:delete" }
    methods:  [POST, DELETE]
